package modelo;

public interface Protocolo {
	final String LOG="LOG";
	
	final String INSERTAR_USUARIO="INSERTARUSUARIO";
	final String INSERTAR_ALQUILER="INSERTARALQUILER";
	
	final String ACTUALIZAR_USUARIO="ACTUALIZARUSUARIO";
	final String ACTUALIZ_ALQUILER="ACTUALIZARALQUILER";
	
	final String BORRAR_USUARIO="BORRARUSUARIO";
	final String BORRAR_ALQUILER="BORRARALQUILER";
	
	final String LISTAR_USUARIO="LISTARUSUARIO";
	final String LISTAR_ALQUILER="LISTARALQUILER";
	final String LISTAR_PISTAS="LISTARPISTAS";
	
	final String LISTAR_USUARIOS="LISTARUSUARIOS";
	final String LISTAR_ALQUILERES="LISTARALQUILERES";

	final String SALIR="SALIR";
}
